LAB05-ED1/Models/ErrorViewModel.cs
using System;

namespace LAB05_ED1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LAB05-ED1/Controllers/HomeController.cs
using LAB05_ED1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LAB05_ED1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LAB05-ED1/Controllers/TwoThreeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Threading.Tasks;
using ClassLibrary;
using LAB05_ED1.Helpers;

namespace LAB05_ED1.Controllers
{
    public class TwoThreeController : Controller
    {
        private IWebHostEnvironment Environment;
        public TwoThreeController(IWebHostEnvironment _environment)
        {
            Environment = _environment;
        }

        

        // GET: TwoThreeController
        public ActionResult Index()
        {
            if (Data.Instance.Searchlist.Count == 0)
                return View(Data.Instance.VehicleTree.ElementList.OrderBy(x => x.LicensePlate));
            else
            {
                List<Vehicle> aux = new List<Vehicle>();
                aux.Add(Data.Instance.Searchlist[0]);
                //var aux = Data.Instance.Searchlist[0];
                Data.Instance.Searchlist.Clear();
                return View(aux);
            }
                
        }

        


        [HttpPost]
        public ActionResult Index(IFormFile File)
        {
            if (File != null)
            {

                ViewBag.File = true;
                string path = Path.Combine(this.Environment.WebRootPath, "Uploads");

                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                string FileName = Path.GetFileName(File.FileName);
                string filePath = Path.Combine(path, FileName);
                FileStream stream = new FileStream(filePath, FileMode.Open, FileAccess.Read);



                string DataList = System.IO.File.ReadAllText(filePath);

                DataList.Trim();
                StreamReader read = new StreamReader(filePath);

                try
                {
                    string line = "";
                    while ((line = read.ReadLine()) != null)
                    {
                        string[] aux = line.Split(",");
                        Vehicle vehicle = new Vehicle
                        {
                            LicensePlate = aux[0],
                            Color = aux[1],
                            Owner = aux[2],
                            Latitude = Convert.ToDouble(aux[3]),
                            Longitude = Convert.ToDouble(aux[4])
                        };


                        Data.Instance.VehicleTree.Root = Data.Instance.VehicleTree.Insert(Data.Instance.VehicleTree.Root, vehicle);
                    }
                }
                catch
                {
                    return Content("There was an error with the file you're trying to import");
                }
            }

            return View();
        }

            // GET: TwoThreeController/Details/5
            public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TwoThreeController/Create
        public ActionResult Create()
        {
            return View(new Vehicle());
        }

        // POST: TwoThreeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                Vehicle vehicle = new Vehicle()
                {
                    LicensePlate = collection["LicensePlate"],
                    Color = collection["Color"],
                    Owner = collection["Owner"],
                    Latitude = Convert.ToDouble(collection["Latitude"]),
                    Longitude = Convert.ToDouble(collection["Longitude"]),
                };

                
                Data.Instance.VehicleTree.Root = Data.Instance.VehicleTree.Insert(Data.Instance.VehicleTree.Root, vehicle);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }



        public Action<Vehicle, Vehicle> EditData = (currentVehicle, EditedVehicle) =>
        {
            currentVehicle.Latitude = EditedVehicle.Latitude;
            currentVehicle.Longitude = EditedVehicle.Longitude;
        };

        // GET: TwoThreeController/Edit/5
        public ActionResult Edit(string id)
        {
            Vehicle aux = new Vehicle
            {
                LicensePlate = id
            };
            return View(Data.Instance.VehicleTree.Search(Data.Instance.VehicleTree.Root, aux));
        }

        [HttpPost]
        public ActionResult Search(string Search)
        {
            string licensePlate = Search;
            Vehicle vehicle = new Vehicle
            {
                LicensePlate = licensePlate
            };

            //List<Vehicle> SearchedVehicle = new List<Vehicle>();

            Data.Instance.Searchlist.Clear();
            Data.Instance.Searchlist.Add(Data.Instance.VehicleTree.Search(Data.Instance.VehicleTree.Root, vehicle));

            
            return RedirectToAction(nameof(Index));
        }




        // POST: TwoThreeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, IFormCollection collection)
        {
            try
            {
                Vehicle newData = new Vehicle
                {
                    LicensePlate = id,
                    Latitude = Convert.ToDouble(collection["Latitude"]),
                    Longitude = Convert.ToDouble(collection["Longitude"])

                };


                Data.Instance.VehicleTree.Edit(Data.Instance.VehicleTree.Root, newData,  EditData);
                Data.Instance.Searchlist.Clear();
                Data.Instance.Searchlist.Add(Data.Instance.VehicleTree.Search(Data.Instance.VehicleTree.Root, newData));
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TwoThreeController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: TwoThreeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

LAB05-ED1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LAB05-ED1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LAB05_ED1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LAB05_ED1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TwoThree" asp-action="Index">Vehicles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LAB05_ED1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

LAB05-ED1/Views/TwoThree/Create.cshtml
@model ClassLibrary.Vehicle

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Vehicle</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LicensePlate" class="control-label"></label>
                <input asp-for="LicensePlate" class="form-control" />
                <span asp-validation-for="LicensePlate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Owner" class="control-label"></label>
                <input asp-for="Owner" class="form-control" />
                <span asp-validation-for="Owner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LAB05-ED1/Views/TwoThree/Edit.cshtml
@model ClassLibrary.Vehicle

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Vehicle</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LicensePlate" class="control-label"></label>
                <input asp-for="LicensePlate" readonly class="form-control" />
                <span asp-validation-for="LicensePlate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" readonly class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Owner" class="control-label"></label>
                <input asp-for="Owner" readonly class="form-control" />
                <span asp-validation-for="Owner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LAB05-ED1/Views/TwoThree/Index.cshtml
@model IEnumerable<ClassLibrary.Vehicle>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
@{
    if (ViewBag.File == null)
    {
        <form asp-controller="TwoThree" asp-action="Index" method="post" enctype="multipart/form-data">
            <input type="file" name="File" accept=".CSV" /> <br /> <br />
            <input class="btn-info text-white" type="submit" value="vehicle list" />
        </form>
        <br />
        <br />
    }
}

<form asp-controller="TwoThree" asp-action="Search" method="post" enctype="multipart/form-data">
    <input type="text" name="Search"/> <br /> <br />
    <input class="btn-info text-white" type="submit" value="Search vehicle" />
</form>
<br />
<br />

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LicensePlate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Owner)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Latitude)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Longitude)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            if (Model != null)
            {



                @foreach (var item in Model)
                {
                    if (item != null)
                    {
                        <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.LicensePlate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Color)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Owner)
                         </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Latitude)
                        </td>
                        <td>
                             @Html.DisplayFor(modelItem => item.Longitude)
                        </td>
                        <td>
                             @Html.ActionLink("Edit", "Edit", new { id = item.LicensePlate }) |
                             @Html.ActionLink("Details", "Details", new { id = item.LicensePlate }) |
                             @Html.ActionLink("Delete", "Delete", new { id = item.LicensePlate })
                        </td>
                        </tr>
                    }
                    
                }

            }
        }
    </tbody>
</table>